import React, { createContext, useContext, useState, useEffect } from 'react';
import { UserState, StakingVault, Transaction, TabType, InvestmentItem } from './types';
import { INVESTMENT_TIERS, BASE_MINING_RATE, RANKS } from './constants';

interface AppContextType {
  user: UserState;
    activeTab: TabType;
      setActiveTab: (tab: TabType) => void;
        investments: InvestmentItem[];
          buyInvestment: (id: string) => void;
            staking: StakingVault;
              stakeAETH: (amount: number) => boolean;
                unstakeAETH: () => void;
                  claimStakingRewards: () => void;
                    transactions: Transaction[];
                      addTransaction: (tx: Omit<Transaction, 'id' | 'timestamp'>) => void;
                        addBalance: (amount: number) => void;
                          deductBalance: (amount: number) => boolean;
                            luckySpinCooldown: number;
                              triggerSpinCooldown: () => void;
                              }

                              const AppContext = createContext<AppContextType | undefined>(undefined);

                              export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
                                const [activeTab, setActiveTab] = useState<TabType>('dashboard');
                                  const [luckySpinCooldown, setLuckySpinCooldown] = useState<number>(0);

                                    const [user, setUser] = useState<UserState>(() => {
                                        const saved = localStorage.getItem('aether_user');
                                            return saved ? JSON.parse(saved) : {
                                                  balance: 100, 
                                                        totalEarned: 100,
                                                              miningRate: BASE_MINING_RATE,
                                                                    rank: 'Bronze Novice',
                                                                          avatar: '🪐'
                                                                              };
                                                                                });

                                                                                  const [investments, setInvestments] = useState<InvestmentItem[]>(() => {
                                                                                      const saved = localStorage.getItem('aether_investments');
                                                                                          return saved ? JSON.parse(saved) : INVESTMENT_TIERS;
                                                                                            });

                                                                                              const [staking, setStaking] = useState<StakingVault>(() => {
                                                                                                  const saved = localStorage.getItem('aether_staking');
                                                                                                      return saved ? JSON.parse(saved) : {
                                                                                                            stakedAmount: 0,
                                                                                                                  accumulatedRewards: 0,
                                                                                                                        lastTick: Date.now(),
                                                                                                                              apy: 240 
                                                                                                                                  };
                                                                                                                                    });

                                                                                                                                      const [transactions, setTransactions] = useState<Transaction[]>(() => {
                                                                                                                                          const saved = localStorage.getItem('aether_txs');
                                                                                                                                              return saved ? JSON.parse(saved) : [];
                                                                                                                                                });

                                                                                                                                                  useEffect(() => { localStorage.setItem('aether_user', JSON.stringify(user)); }, [user]);
                                                                                                                                                    useEffect(() => { localStorage.setItem('aether_investments', JSON.stringify(investments)); }, [investments]);
                                                                                                                                                      useEffect(() => { localStorage.setItem('aether_staking', JSON.stringify(staking)); }, [staking]);
                                                                                                                                                        useEffect(() => { localStorage.setItem('aether_txs', JSON.stringify(transactions)); }, [transactions]);

                                                                                                                                                          useEffect(() => {
                                                                                                                                                              const interval = setInterval(() => {
                                                                                                                                                                    const currentMiningRate = investments.reduce((acc, inv) => acc + (inv.level * inv.basePayout), BASE_MINING_RATE);
                                                                                                                                                                          const miningAccrual = currentMiningRate / 10;

                                                                                                                                                                                let stakingAccrual = 0;
                                                                                                                                                                                      if (staking.stakedAmount > 0) {
                                                                                                                                                                                              stakingAccrual = staking.stakedAmount * (staking.apy / 100) / (31536000 * 10);
                                                                                                                                                                                                    }

                                                                                                                                                                                                          setUser(prev => {
                                                                                                                                                                                                                  const newBalance = prev.balance + miningAccrual;
                                                                                                                                                                                                                          const currentRank = RANKS.reduce((selected, r) => newBalance >= r.minBalance ? r.name : selected, RANKS[0].name);
                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                            ...prev,
                                                                                                                                                                                                                                                      balance: newBalance,
                                                                                                                                                                                                                                                                totalEarned: prev.totalEarned + miningAccrual,
                                                                                                                                                                                                                                                                          miningRate: currentMiningRate,
                                                                                                                                                                                                                                                                                    rank: currentRank
                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                        if (staking.stakedAmount > 0) {
                                                                                                                                                                                                                                                                                                                setStaking(prev => ({
                                                                                                                                                                                                                                                                                                                          ...prev,
                                                                                                                                                                                                                                                                                                                                    accumulatedRewards: prev.accumulatedRewards + stakingAccrual,
                                                                                                                                                                                                                                                                                                                                              lastTick: Date.now()
                                                                                                                                                                                                                                                                                                                                                      }));
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                }, 100);

                                                                                                                                                                                                                                                                                                                                                                    return () => clearInterval(interval);
                                                                                                                                                                                                                                                                                                                                                                      }, [investments, staking.stakedAmount, staking.apy]);

                                                                                                                                                                                                                                                                                                                                                                        useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                            if (luckySpinCooldown > 0) {
                                                                                                                                                                                                                                                                                                                                                                                  const timer = setTimeout(() => setLuckySpinCooldown(prev => prev - 1), 1000);
                                                                                                                                                                                                                                                                                                                                                                                        return () => clearTimeout(timer);
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                              }, [luckySpinCooldown]);

                                                                                                                                                                                                                                                                                                                                                                                                const addBalance = (amount: number) => {
                                                                                                                                                                                                                                                                                                                                                                                                    setUser(prev => ({ ...prev, balance: prev.balance + amount, totalEarned: prev.totalEarned + amount }));
                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                        const deductBalance = (amount: number): boolean => {
                                                                                                                                                                                                                                                                                                                                                                                                            if (user.balance < amount) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                setUser(prev => ({ ...prev, balance: prev.balance - amount }));
                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                        const buyInvestment = (id: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                            const itemIndex = investments.findIndex(inv => inv.id === id);
                                                                                                                                                                                                                                                                                                                                                                                                                                if (itemIndex === -1) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                    const item = investments[itemIndex];
                                                                                                                                                                                                                                                                                                                                                                                                                                        const currentCost = Math.round(item.cost * Math.pow(1.4, item.level));

                                                                                                                                                                                                                                                                                                                                                                                                                                            if (deductBalance(currentCost)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const updated = [...investments];
                                                                                                                                                                                                                                                                                                                                                                                                                                                        updated[itemIndex] = { ...item, level: item.level + 1 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                              setInvestments(updated);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    addTransaction({ type: 'Claim', amount: currentCost, currency: 'AETH', status: 'Completed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const stakeAETH = (amount: number): boolean => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (deductBalance(amount)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setStaking(prev => ({ ...prev, stakedAmount: prev.stakedAmount + amount, lastTick: Date.now() }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            addTransaction({ type: 'Stake', amount, currency: 'AETH', status: 'Completed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const unstakeAETH = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (staking.stakedAmount <= 0) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const totalReturn = staking.stakedAmount + staking.accumulatedRewards;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          addBalance(totalReturn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setStaking({ stakedAmount: 0, accumulatedRewards: 0, lastTick: Date.now(), apy: 240 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  addTransaction({ type: 'Withdraw', amount: totalReturn, currency: 'AETH', status: 'Completed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const claimStakingRewards = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (staking.accumulatedRewards <= 0) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              addBalance(staking.accumulatedRewards);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setStaking(prev => ({ ...prev, accumulatedRewards: 0, lastTick: Date.now() }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      addTransaction({ type: 'Claim', amount: staking.accumulatedRewards, currency: 'AETH', status: 'Completed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const addTransaction = (tx: Omit<Transaction, 'id' | 'timestamp'>) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const newTx: Transaction = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...tx,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: `tx_${Math.random().toString(36).substr(2, 9)}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timestamp: new Date().toLocaleTimeString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTransactions(prev => [newTx, ...prev].slice(0, 20));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const triggerSpinCooldown = () => setLuckySpinCooldown(30);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <AppContext.Provider value={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user, activeTab, setActiveTab, investments, buyInvestment,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              staking, stakeAETH, unstakeAETH, claimStakingRewards,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transactions, addTransaction, addBalance, deductBalance,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          luckySpinCooldown, triggerSpinCooldown
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </AppContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export const useApp = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const context = useContext(AppContext);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!context) throw new Error('useApp must be used within an AppProvider');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return context;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                