import React, { useState, useEffect } from 'react';
import { useApp } from '../AppContext';
import { GlassCard } from '../components/ui/GlassCard';
import { GlowButton } from '../components/ui/GlowButton';
import { StatCard } from '../components/ui/StatCard';
import { SPIN_REWARDS } from '../constants';

export const DashboardTab: React.FC = () => {
  const { 
      user, staking, stakeAETH, unstakeAETH, claimStakingRewards,
          luckySpinCooldown, triggerSpinCooldown, addBalance 
            } = useApp();

              const [stakeInput, setStakeInput] = useState<string>('');
                const [spinResult, setSpinResult] = useState<string>('SPIN');
                  const [isSpinning, setIsSpinning] = useState<boolean>(false);
                    const [stakingRewardsLive, setStakingRewardsLive] = useState<number>(0);

                      // تحديث العداد الحي لجوائز الستيكنج كل 100 مللي ثانية لمنح إحساس التفاعل الفوري
                        useEffect(() => {
                            const interval = setInterval(() => {
                                  setStakingRewardsLive(staking.accumulatedRewards);
                                      }, 100);
                                          return () => clearInterval(interval);
                                            }, [staking.accumulatedRewards]);

                                              const handleStake = (e: React.FormEvent) => {
                                                  e.preventDefault();
                                                      const amount = parseFloat(stakeInput);
                                                          if (!isNaN(amount) && amount > 0) {
                                                                const success = stakeAETH(amount);
                                                                      if (success) setStakeInput('');
                                                                            else alert('Insufficient AETH balance!');
                                                                                }
                                                                                  };

                                                                                    const handleLuckySpin = () => {
                                                                                        if (luckySpinCooldown > 0 || isSpinning) return;

                                                                                            setIsSpinning(true);
                                                                                                let counter = 0;
                                                                                                    
                                                                                                        // أنيميشن المحاكاة السريعة لعجلة الحظ قبل الاستقرار على رقم
                                                                                                            const spinInterval = setInterval(() => {
                                                                                                                  const randomFakeReward = SPIN_REWARDS[Math.floor(Math.random() * SPIN_REWARDS.length)];
                                                                                                                        setSpinResult(`🌀 ${randomFakeReward}`);
                                                                                                                              counter++;

                                                                                                                                    if (counter > 15) {
                                                                                                                                            clearInterval(spinInterval);
                                                                                                                                                    const finalReward = SPIN_REWARDS[Math.floor(Math.random() * SPIN_REWARDS.length)];
                                                                                                                                                            setSpinResult(`🎉 +${finalReward} AETH`);
                                                                                                                                                                    addBalance(finalReward);
                                                                                                                                                                            triggerSpinCooldown();
                                                                                                                                                                                    setIsSpinning(false);
                                                                                                                                                                                          }
                                                                                                                                                                                              }, 100);
                                                                                                                                                                                                };

                                                                                                                                                                                                  return (
                                                                                                                                                                                                      <div className="space-y-5 pb-24 animate-fade-in">
                                                                                                                                                                                                            {/* قسم الإحصائيات العلوية */}
                                                                                                                                                                                                                  <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                          <StatCard 
                                                                                                                                                                                                                                    label="AETH BALANCE" 
                                                                                                                                                                                                                                              value={user.balance.toFixed(4)} 
                                                                                                                                                                                                                                                        icon="🪐" 
                                                                                                                                                                                                                                                                  color="cyan"
                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                  <StatCard 
                                                                                                                                                                                                                                                                                            label="MINING SPEED" 
                                                                                                                                                                                                                                                                                                      value={`+${(user.miningRate * 10).toFixed(3)}/s`} 
                                                                                                                                                                                                                                                                                                                icon="⚡" 
                                                                                                                                                                                                                                                                                                                          color="blue"
                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                              {/* عجلة الحظ التفاعلية: Holographic Vortex Lucky Spin */}
                                                                                                                                                                                                                                                                                                                                                    <GlassCard glowColor="cyan" className="text-center relative overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                            <div className="absolute top-0 right-0 bg-cyan-500/10 text-cyan-400 border-b border-l border-cyan-500/20 px-3 py-1 text-[10px] font-bold rounded-bl-xl tracking-wider">
                                                                                                                                                                                                                                                                                                                                                                      LIVE NODE
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="text-sm font-bold text-slate-300 mb-1 flex浏览 items-center justify-center gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                🎰 Vortex Singularity Spin
                                                                                                                                                                                                                                                                                                                                                                                                        </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-xs text-slate-400 mb-4">Quantum calibration outputs instant rewards every 30s</p>
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={`w-28 h-28 rounded-full border-2 border-dashed border-cyan-500/40 flex items-center justify-center font-black text-sm tracking-wide text-cyan-400 backdrop-blur-3xl bg-cyan-950/20 ${isSpinning ? 'animate-spin' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {spinResult}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <GlowButton 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variant="cyan" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fullWidth 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleLuckySpin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={luckySpinCooldown > 0 || isSpinning}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {luckySpinCooldown > 0 ? `Calibration Link in ${luckySpinCooldown}s` : 'Initiate Quantum Spin'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </GlassCard>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* نظام الاستثمار: Quantum Staking Compounder */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <GlassCard glowColor="purple">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-between items-center mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-sm font-bold text-slate-200">🔮 Quantum Compounder Vault</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[11px] text-slate-400">Yield engine with instantaneous live distribution</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-purple-500/20 border border-purple-500/40 text-purple-300 font-bold px-2 py-1 rounded text-xs animate-pulse">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              240% APY
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* عرض الرصيد المستثمر والأرباح الحية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-2 bg-black/30 p-3 rounded-xl border border-white/5 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-[10px] text-slate-500 block">STAKED CAPITAL</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-sm font-bold text-white">{staking.stakedAmount.toFixed(2)} AETH</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[10px] text-purple-400 block">LIVE INTEREST ACCRUED</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-sm font-bold text-purple-400 tracking-wider">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            +{stakingRewardsLive.toFixed(6)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* نموذج الإيداع الفوري */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={handleStake} className="flex gap-2 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="relative flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="number" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Amount to Lock"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={stakeInput}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setStakeInput(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white focus:outline-none focus:border-purple-500/50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setStakeInput(user.balance.toFixed(2))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="absolute right-2 top-2 bg-purple-500/20 hover:bg-purple-500/40 text-purple-300 text-[10px] font-bold px-2 py-1 rounded transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MAX
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <GlowButton variant="purple" type="submit" className="py-2.5 px-5 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Stake
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* أزرار السحب والمطالبة */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <GlowButton 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      variant="blue" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="py-2 text-xs" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={staking.accumulatedRewards <= 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={claimStakingRewards}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Claim Interest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <GlowButton 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                variant="danger" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="py-2 text-xs" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={staking.stakedAmount <= 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={unstakeAETH}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Unstake Capital & ROI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </GlassCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        