import React from 'react';
import { GlassCard } from '../components/ui/GlassCard';
import { GlowButton } from '../components/ui/GlowButton';

export const ReferralTab: React.FC = () => {
  // بيانات افتراضية ممتازة لمحاكاة قائمة الأصدقاء المشتركين
    const mockReferrals = [
        { id: '1', username: '@alex_crypto', status: 'Active', earned: 45.5 },
            { id: '2', username: '@ton_whale33', status: 'Active', earned: 120.0 },
                { id: '3', username: '@shadow_miner', status: 'Inactive', earned: 0.0 }
                  ];

                    const handleShareLink = () => {
                        alert('Referral link copied to clipboard! Share it on Telegram to earn 10% network bonuses.');
                          };

                            return (
                                <div className="space-y-4 pb-24 animate-fade-in">
                                      <div className="p-1">
                                              <h2 className="text-base font-bold text-white mb-1">👥 Neural Network Affiliates</h2>
                                                      <p className="text-xs text-slate-400">Expand your cluster to receive a 10% instant dividends match on all affiliate mining yields.</p>
                                                            </div>

                                                                  {/* كرت عرض الرابط والإحصائيات */}
                                                                        <GlassCard glowColor="purple" className="space-y-4">
                                                                                <div className="grid grid-cols-3 gap-2 text-center">
                                                                                          <div className="bg-white/5 border border-white/5 p-2 rounded-xl">
                                                                                                      <span className="text-[9px] text-slate-500 block">TOTAL REFS</span>
                                                                                                                  <span className="text-base font-bold text-white">3</span>
                                                                                                                            </div>
                                                                                                                                      <div className="bg-white/5 border border-white/5 p-2 rounded-xl">
                                                                                                                                                  <span className="text-[9px] text-purple-400 block">ACTIVE NODES</span>
                                                                                                                                                              <span className="text-base font-bold text-purple-400">2</span>
                                                                                                                                                                        </div>
                                                                                                                                                                                  <div className="bg-white/5 border border-white/5 p-2 rounded-xl">
                                                                                                                                                                                              <span className="text-[9px] text-cyan-400 block">BONUS EARNED</span>
                                                                                                                                                                                                          <span className="text-base font-bold text-cyan-400">165.5</span>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                    <div className="bg-black/30 p-3 rounded-xl border border-white/5">
                                                                                                                                                                                                                                              <span className="text-[10px] text-slate-500 block mb-1">YOUR UNIQUE INVITE LINK</span>
                                                                                                                                                                                                                                                        <div className="text-xs text-slate-300 font-mono truncate bg-black/40 p-2 rounded border border-white/5 select-all">
                                                                                                                                                                                                                                                                    https://t.me/AetherForgeBot/app?startapp=ref333x
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                              <GlowButton variant="purple" fullWidth onClick={handleShareLink}>
                                                                                                                                                                                                                                                                                                        🔗 Dispatch Telegram Invite Link
                                                                                                                                                                                                                                                                                                                </GlowButton>
                                                                                                                                                                                                                                                                                                                      </GlassCard>

                                                                                                                                                                                                                                                                                                                            {/* قائمة الشبكة */}
                                                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xs font-bold text-slate-400 px-1">Network Sub-Nodes</h3>
                                                                                                                                                                                                                                                                                                                                                  {mockReferrals.map((ref) => (
                                                                                                                                                                                                                                                                                                                                                            <div key={ref.id} className="backdrop-blur-md bg-white/5 border border-white/10 rounded-xl p-3 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                      <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                      👤
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs font-bold text-white block">{ref.username}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`text-[9px] font-medium ${ref.status === 'Active' ? 'text-emerald-400' : 'text-slate-500'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ● Node Status: {ref.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-[9px] text-slate-500 block">GENERATED Yield</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-xs font-bold text-cyan-400">+{ref.earned.toFixed(1)} AETH</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                