import React, { useState } from 'react';
import { useApp } from '../AppContext';
import { GlassCard } from '../components/ui/GlassCard';
import { GlowButton } from '../components/ui/GlowButton';

export const WalletTab: React.FC = () => {
  const { user, addBalance, deductBalance, addTransaction, transactions } = useApp();
    const [walletConnected, setWalletConnected] = useState<boolean>(false);
      const [tonAddress, setTonAddress] = useState<string>('');
        const [swapAmount, setSwapAmount] = useState<string>('');
          const [isProcessing, setIsProcessing] = useState<boolean>(false);

            const handleConnectWallet = () => {
                setIsProcessing(true);
                    setTimeout(() => {
                          setWalletConnected(true);
                                setTonAddress('UQAr...9XzB');
                                      addTransaction({ type: 'Deposit', amount: 0, currency: 'TON_WALLET', status: 'Completed' });
                                            setIsProcessing(false);
                                                }, 1500);
                                                  };

                                                    const handleSwap = (e: React.FormEvent) => {
                                                        e.preventDefault();
                                                            const amount = parseFloat(swapAmount);
                                                                if (isNaN(amount) || amount <= 0) return;

                                                                    // محاكاة تحويل TON إلى عملة التطبيق AETH (كل 1 TON = 250 AETH)
                                                                        setIsProcessing(true);
                                                                            setTimeout(() => {
                                                                                  const aethGained = amount * 250;
                                                                                        addBalance(aethGained);
                                                                                              addTransaction({ type: 'Swap', amount: amount, currency: `TON → ${aethGained} AETH`, status: 'Completed' });
                                                                                                    setSwapAmount('');
                                                                                                          setIsProcessing(false);
                                                                                                                alert(`Successfully swapped ${amount} TON for ${aethGained} AETH!`);
                                                                                                                    }, 1200);
                                                                                                                      };

                                                                                                                        return (
                                                                                                                            <div className="space-y-4 pb-24 animate-fade-in">
                                                                                                                                  <div className="p-1">
                                                                                                                                          <h2 className="text-base font-bold text-white mb-1">💎 TVM Settlement Bridge</h2>
                                                                                                                                                  <p className="text-xs text-slate-400">Secure on-chain integrations, deposits, and automated asset routing parameters.</p>
                                                                                                                                                        </div>

                                                                                                                                                              {/* اتصال المحفظة التناظري الفاخر */}
                                                                                                                                                                    <GlassCard glowColor={walletConnected ? 'blue' : 'none'} className="text-center py-6">
                                                                                                                                                                            <div className="w-12 h-12 rounded-2xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-xl text-blue-400 mx-auto mb-3 shadow-inner">
                                                                                                                                                                                      💎
                                                                                                                                                                                              </div>
                                                                                                                                                                                                      
                                                                                                                                                                                                              {walletConnected ? (
                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                    <h3 className="text-sm font-bold text-white">TON Wallet Integrated</h3>
                                                                                                                                                                                                                                                <p className="text-xs font-mono text-blue-400 mt-1 bg-blue-950/30 px-3 py-1 rounded-full inline-block border border-blue-500/20">
                                                                                                                                                                                                                                                              {tonAddress}
                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                  <h3 className="text-sm font-bold text-slate-300">No Web3 Anchor Detected</h3>
                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-slate-500 mb-4 px-4">Link your decentralised TON hub to configure simulated liquidity paths.</p>
                                                                                                                                                                                                                                                                                                                                          <GlowButton variant="blue" onClick={handleConnectWallet} disabled={isProcessing} className="mx-auto px-6 py-2 text-xs">
                                                                                                                                                                                                                                                                                                                                                        {isProcessing ? 'Connecting...' : 'Connect TON Space Wallet'}
                                                                                                                                                                                                                                                                                                                                                                    </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                            </GlassCard>

                                                                                                                                                                                                                                                                                                                                                                                                  {/* لوحة تحويل الكريبتو والمبادلة */}
                                                                                                                                                                                                                                                                                                                                                                                                        {walletConnected && (
                                                                                                                                                                                                                                                                                                                                                                                                                <GlassCard glowColor="cyan">
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xs font-bold text-slate-300 mb-3 flex items-center gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                      ⚡ Decoupled Token Liquidity Swapper
                                                                                                                                                                                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={handleSwap} className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="text-[10px] text-slate-500 block mb-1 font-medium">PAYING ASSET (SIMULATED TON)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="number" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="0.00"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={swapAmount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setSwapAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white focus:outline-none focus:border-cyan-500/50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="absolute right-3 top-2.5 text-xs font-bold text-slate-400">TON</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-center text-slate-600 text-xs py-0.5">↓ rate: 1 TON = 250 AETH ↓</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="text-[10px] text-slate-500 block mb-1 font-medium">RECEIVING ASSET</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="w-full bg-black/40 border border-white/5 rounded-xl px-3 py-2.5 text-sm text-cyan-400 font-bold flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>{swapAmount ? (parseFloat(swapAmount) * 250).toLocaleString() : '0.00'}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs font-bold text-slate-400">AETH</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <GlowButton variant="cyan" type="submit" fullWidth disabled={isProcessing || !swapAmount}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isProcessing ? 'Routing Transaction...' : 'Execute Liquidity Swap'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </GlassCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* سجل الحركات المالي للـ Blockchain Ledger المدمج */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-xs font-bold text-slate-400 px-1">Recent Ledger Ledger</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <GlassCard className="p-2 space-y-1 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {transactions.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-slate-600 text-center py-4">No recent ledger data compiled.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transactions.map((tx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={tx.id} className="flex justify-between items-center text-[11px] py-1.5 border-b border-white/5 last:border-none px-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className={`font-bold block ${tx.type === 'Stake' ? 'text-purple-400' : tx.type === 'Swap' ? 'text-cyan-400' : 'text-slate-300'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {tx.type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-[9px] text-slate-500 font-mono">{tx.timestamp}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-right font-mono">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-white font-bold">{tx.amount > 0 ? tx.amount : ''} {tx.currency}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-[9px] text-emerald-400 block">✔ Synced</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </GlassCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                