import React from 'react';
import { useApp } from '../AppContext';
import { GlassCard } from '../components/ui/GlassCard';
import { GlowButton } from '../components/ui/GlowButton';

export const InvestTab: React.FC = () => {
  const { investments, buyInvestment, user } = useApp();

    return (
        <div className="space-y-4 pb-24 animate-fade-in">
              <div className="p-1">
                      <h2 className="text-base font-bold text-white mb-1">⚡ Energy Overclock Center</h2>
                              <p className="text-xs text-slate-400">Procure high-performance hardware modules to escalate passive AETH synthesis.</p>
                                    </div>

                                          {investments.map((inv) => {
                                                  // حساب التكلفة التصاعدية لكل ترقية هندسية
                                                          const currentCost = Math.round(inv.cost * Math.pow(1.4, inv.level));
                                                                  const canAfford = user.balance >= currentCost;

                                                                          return (
                                                                                    <GlassCard key={inv.id} className="flex flex-col gap-3 relative">
                                                                                                <div className="flex justify-between items-start">
                                                                                                              <div className="flex gap-3 items-center">
                                                                                                                              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500/10 to-purple-500/10 border border-white/10 flex items-center justify-center font-bold text-base text-blue-400 shadow-inner">
                                                                                                                                                {inv.icon === 'Cpu' ? '💻' : inv.icon === 'Zap' ? '⚡' : inv.icon === 'Atom' ? '⚛️' : '🧠'}
                                                                                                                                                                </div>
                                                                                                                                                                                <div>
                                                                                                                                                                                                  <h3 className="text-sm font-bold text-white">{inv.name}</h3>
                                                                                                                                                                                                                    <div className="flex gap-2 items-center mt-0.5">
                                                                                                                                                                                                                                        <span className="text-[10px] bg-white/5 border border-white/10 text-slate-400 px-1.5 py-0.5 rounded">
                                                                                                                                                                                                                                                              Lvl {inv.level}
                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                      <span className="text-[10px] text-emerald-400 font-medium">
                                                                                                                                                                                                                                                                                                                            +{((inv.basePayout) * 10).toFixed(3)} AETH/s
                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-[10px] text-slate-500 block">UPGRADE COST</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className={`text-xs font-bold ${canAfford ? 'text-cyan-400' : 'text-slate-400'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {currentCost.toLocaleString()} AETH
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <GlowButton 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    variant={canAfford ? 'blue' : 'danger'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fullWidth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={!canAfford}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => buyInvestment(inv.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="py-2 text-xs"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {canAfford ? '⚡ Deploy Hardware Overclock' : '❌ Insufficient Micro-Credits'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </GlowButton>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </GlassCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                