import os
from motor.motor_asyncio import AsyncIOMotorClient
import datetime

# قراءة رابط الاتصال بـ MongoDB من متغيرات البيئة (يمكنك استخدام MongoDB Atlas المجاني)
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
DB_NAME = "aetherforge_db"

client = AsyncIOMotorClient(MONGO_URI)
db = client[DB_NAME]
users_col = db["users"]
transactions_col = db["transactions"]

async def get_or_create_user(telegram_id: int, username: str, first_name: str):
    """
        جلب بيانات المستخدم الحالية من MongoDB، وإذا كان جديداً يتم إنشاؤه بالقيم الابتدائية
            """
                user = await users_col.find_one({"telegram_id": telegram_id})
                    
                        if not user:
                                # البيانات الابتدائية للمستخدم الجديد
                                        user = {
                                                    "telegram_id": telegram_id,
                                                                "username": username or "Unknown",
                                                                            "first_name": first_name,
                                                                                        "balance": 100.0,          # رصيد ترحيبي ابتدائي
                                                                                                    "mining_rate": 0.001,      # السرعة الابتدائية الأساسية
                                                                                                                "rank": "Bronze Synthesizer",
                                                                                                                            "avatar": "🪐",
                                                                                                                                        "last_active": datetime.datetime.utcnow(),
                                                                                                                                                    "created_at": datetime.datetime.utcnow(),
                                                                                                                                                                "investments": [
                                                                                                                                                                                {"id": "cpu", "name": "Quantum CPU Thread", "level": 1, "base_payout": 0.001, "cost": 50},
                                                                                                                                                                                                {"id": "zap", "name": "Tesla Coil Node", "level": 0, "base_payout": 0.005, "cost": 250},
                                                                                                                                                                                                                {"id": "atom", "name": "Fusion Core Reactor", "level": 0, "base_payout": 0.025, "cost": 1250},
                                                                                                                                                                                                                                {"id": "brain", "name": "AI Cluster Core", "level": 0, "base_payout": 0.125, "cost": 6500}
                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                        "staking": {
                                                                                                                                                                                                                                                                        "staked_amount": 0.0,
                                                                                                                                                                                                                                                                                        "accumulated_rewards": 0.0,
                                                                                                                                                                                                                                                                                                        "last_claim": datetime.datetime.utcnow()
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                "referred_by": None
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                await users_col.insert_one(user)
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        return user

                                                                                                                                                                                                                                                                                                                                                        async def update_user_balance(telegram_id: int, amount: float):
                                                                                                                                                                                                                                                                                                                                                            """تحديث رصيد المستخدم بالزيادة أو النقصان"""
                                                                                                                                                                                                                                                                                                                                                                await users_col.update_one(
                                                                                                                                                                                                                                                                                                                                                                        {"telegram_id": telegram_id},
                                                                                                                                                                                                                                                                                                                                                                                {"$inc": {"balance": amount}, "$set": {"last_active": datetime.datetime.utcnow()}}
                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                    async def log_transaction(telegram_id: int, tx_type: str, amount: float, currency: str, status: str = "Completed"):
                                                                                                                                                                                                                                                                                                                                                                                        """تسجيل العمليات في سجل البلوكتشين التناظري للمستخدم"""
                                                                                                                                                                                                                                                                                                                                                                                            tx = {
                                                                                                                                                                                                                                                                                                                                                                                                    "telegram_id": telegram_id,
                                                                                                                                                                                                                                                                                                                                                                                                            "type": tx_type,
                                                                                                                                                                                                                                                                                                                                                                                                                    "amount": amount,
                                                                                                                                                                                                                                                                                                                                                                                                                            "currency": currency,
                                                                                                                                                                                                                                                                                                                                                                                                                                    "status": status,
                                                                                                                                                                                                                                                                                                                                                                                                                                            "timestamp": datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    await transactions_col.insert_one(tx)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return tx
                                                                                                                                                                                                                                                                                                                                                                                                                                                        